SELECT
   SUM(l_extendedprice)/7.0 AS AVG_YEARLY
 FROM 
   LINEITEM
  ,PART
 WHERE
   P_PARTKEY  = L_PARTKEY
 AND  P_BRAND  = N'Brand#43'
 AND  P_CONTAINER = N'LG BAG'
 AND  L_QUANTITY  <
   (SELECT   0.2 * AVG(L_QUANTITY)
    FROM  LINEITEM
    WHERE  L_PARTKEY = P_PARTKEY
   );
